"""Add columns to user table

Revision ID: 18239a3befe0
Revises: de137d7e8ef9
Create Date: 2016-02-24 19:09:47.221123

"""

# revision identifiers, used by Alembic.
revision = '18239a3befe0'
down_revision = 'de137d7e8ef9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('last_update', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_update')
    op.drop_column('user', 'create_date')
    ### end Alembic commands ###
