"""Add item table

Revision ID: 34378a15d588
Revises: 97f2d8b76246
Create Date: 2016-04-28 13:34:38.387391

"""

# revision identifiers, used by Alembic.
revision = '34378a15d588'
down_revision = '97f2d8b76246'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('_uuid', sa.Unicode(length=36), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_uuid', name='item_uuid_unique')
    )
    op.create_unique_constraint('category_name_unique', 'category', ['name'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.drop_constraint('category_name_unique', 'category', type_='unique')
    op.drop_table('item')
    ### end Alembic commands ###
