"""change column to BigInteger

Revision ID: 97f2d8b76246
Revises: 18239a3befe0
Create Date: 2016-02-25 20:38:21.952978

"""

# revision identifiers, used by Alembic.
revision = '97f2d8b76246'
down_revision = '18239a3befe0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id', type_=sa.BigInteger, existing_type=sa.Integer)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id', type_=sa.Integer, existing_type=sa.BigInteger)
    ### end Alembic commands ###
