"""Add user login and provider

Revision ID: bdcc67c48b91
Revises: f8ed1be5f858
Create Date: 2016-04-28 16:06:12.611055

"""

# revision identifiers, used by Alembic.
revision = 'bdcc67c48b91'
down_revision = 'f8ed1be5f858'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oa_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=20), nullable=False),
    sa.Column('description', sa.Unicode(length=250), nullable=True),
    sa.Column('application_id', sa.Unicode(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('oa_provider_id', sa.Integer(), nullable=True),
    sa.Column('login_date', sa.DateTime(), nullable=False),
    sa.Column('logout_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oa_provider_id'], ['oa_provider.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login')
    op.drop_table('oa_provider')
    ### end Alembic commands ###
