"""Add forieng key to category.

Revision ID: f8ed1be5f858
Revises: 34378a15d588
Create Date: 2016-04-28 14:00:30.123563

"""

# revision identifiers, used by Alembic.
revision = 'f8ed1be5f858'
down_revision = '34378a15d588'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('item_category_id_fkey', 'item', 'category', ['category_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_category_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'category_id')
    ### end Alembic commands ###
